<a href="https://colab.research.google.com/github/meenakshireddy2903-cpu/DataAnalysis_Tasks/blob/main/DataCleaning_Task(cafe_sales).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#DATACLEANING

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df = pd.read_csv("/content/dirty_cafe_sales.csv")

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  object
 1   Item              9667 non-null   object
 2   Quantity          9862 non-null   object
 3   Price Per Unit    9821 non-null   object
 4   Total Spent       9827 non-null   object
 5   Payment Method    7421 non-null   object
 6   Location          6735 non-null   object
 7   Transaction Date  9841 non-null   object
dtypes: object(8)
memory usage: 625.1+ KB

In [ ]:
df.isnull().sum()

Transaction ID         0
Item                 333
Quantity             138
Price Per Unit       179
Total Spent          173
Payment Method      2579
Location            3265
Transaction Date     159
dtype: int64

In [ ]:
df.dropna(inplace=True)
df

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9984,TXN_3142496,Smoothie,UNKNOWN,4.0,4.0,Cash,Takeaway,2023-07-27
9986,TXN_2858441,Sandwich,2,4.0,8.0,Credit Card,In-store,2023-12-14
9991,TXN_3897619,Sandwich,3,4.0,12.0,Cash,Takeaway,2023-02-24
9992,TXN_2739140,Smoothie,4,4.0,16.0,UNKNOWN,In-store,2023-07-05
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

In [ ]:
df.isnull().sum()

Transaction ID      0
Item                0
Quantity            0
Price Per Unit      0
Total Spent         0
Payment Method      0
Location            0
Transaction Date    0
dtype: int64

In [ ]:
df.shape

(4550, 8)

In [ ]:
df.drop_duplicates(inplace = True)
df.shape

(4550, 8)

**Handling Transaction id column**

In [ ]:
df["Transaction ID"].unique()

array(['TXN_1961373', 'TXN_4977031', 'TXN_4271903', ..., 'TXN_3897619',
       'TXN_2739140', 'TXN_6170729'], dtype=object)

In [ ]:
df["Item"].unique()

array(['Coffee', 'Cake', 'Cookie', 'Salad', 'UNKNOWN', 'Sandwich',
       'Juice', 'Smoothie', 'ERROR', 'Tea'], dtype=object)

**Handling Item column**

In [ ]:
df['Item'] = df['Item'].replace("UNKNOWN","Juice")
df['Item'].unique()

array(['Coffee', 'Cake', 'Cookie', 'Salad', 'Juice', 'Sandwich',
       'Smoothie', 'ERROR', 'Tea'], dtype=object)

In [ ]:
df['Item'].mode()

0    Juice
Name: Item, dtype: object

In [ ]:
df['Item'] = df['Item'].replace("ERROR","Juice")
df['Item'].unique()

array(['Coffee', 'Cake', 'Cookie', 'Salad', 'Juice', 'Sandwich',
       'Smoothie', 'Tea'], dtype=object)

**Handling Quantity Column**

In [ ]:
df["Quantity"].unique()

array(['2', '4', '3', '5', 'ERROR', '1', 'UNKNOWN'], dtype=object)

In [ ]:
#Handling Quantity column
df['Quantity'].mode()

0    5
Name: Quantity, dtype: object

In [ ]:
df['Quantity']=df['Quantity'].replace('ERROR',5)

In [ ]:
df['Quantity']=df['Quantity'].replace('UNKNOWN',5)

In [ ]:
df['Quantity'].unique()

array(['2', '4', '3', '5', 5, '1'], dtype=object)

**Handling Price per unit column**

In [ ]:
df['Price Per Unit'].unique()

array(['2.0', '3.0', '1.0', '5.0', '4.0', '1.5', 'UNKNOWN', 'ERROR'],
      dtype=object)

In [ ]:
df['Price Per Unit'] = df['Price Per Unit'].replace('ERROR',3)
df['Price Per Unit'] = df['Price Per Unit'].replace('UNKNOWN',3)
df["Price Per Unit"] = df["Price Per Unit"].astype(float)
avg_price = round(df['Price Per Unit'].mean())
avg_price

3

In [ ]:
df['Price Per Unit'].unique()

array([2. , 3. , 1. , 5. , 4. , 1.5])

**Handling total spent column**

In [ ]:
df['Total Spent'].unique()

array(['4.0', '12.0', 'ERROR', '10.0', '9.0', '16.0', '25.0', '8.0',
       '15.0', '6.0', '20.0', '5.0', '2.0', '3.0', '1.0', 'UNKNOWN',
       '7.5', '4.5', '1.5'], dtype=object)

In [ ]:
df['Total Spent'] = df['Total Spent'].replace('ERROR',0)
df['Total Spent'] = df['Total Spent'].replace('UNKNOWN',0)
df['Total Spent'] = df['Total Spent'].astype(float)
avg_total = round(df['Total Spent'].mean())
avg_total

9

In [ ]:
df['Total Spent'] = df['Total Spent'].replace('ERROR',avg_total)
df['Total Spent'] = df['Total Spent'].replace('UNKNOWN',avg_total)

In [ ]:
df['Total Spent'].unique()

array([ 4. , 12. ,  0. , 10. ,  9. , 16. , 25. ,  8. , 15. ,  6. , 20. ,
        5. ,  2. ,  3. ,  1. ,  7.5,  4.5,  1.5])

In [ ]:
df['Total Spent'] = df['Total Spent'].replace(0.0,avg_total)

In [ ]:
df['Total Spent'].unique()

array([ 4. , 12. ,  9. , 10. , 16. , 25. ,  8. , 15. ,  6. , 20. ,  5. ,
        2. ,  3. ,  1. ,  7.5,  4.5,  1.5])

**Handling Payment Method column**

In [ ]:
df['Payment Method'].unique()

array(['Credit Card', 'Cash', 'UNKNOWN', 'Digital Wallet', 'ERROR'],
      dtype=object)

In [ ]:
df['Payment Method'].mode()

0    Digital Wallet
Name: Payment Method, dtype: object

In [ ]:
df['Payment Method'] = df['Payment Method'].replace('UNKNOWN','Digital Wallet')
df['Payment Method'] = df['Payment Method'].replace('ERROR','Digital Wallet')
df['Payment Method'].unique()

array(['Credit Card', 'Cash', 'Digital Wallet'], dtype=object)

**handling Location column**

In [ ]:
df['Location'].unique()

array(['Takeaway', 'In-store', 'UNKNOWN', 'ERROR'], dtype=object)

In [ ]:
df['Location'].mode()

0    In-store
1    Takeaway
Name: Location, dtype: object

In [ ]:
df['Location'] = df['Location'].replace('UNKNOWN','In-store')
df['Location'] = df['Location'].replace('ERROR','Takeaway')

In [ ]:
df['Location'].unique()

array(['Takeaway', 'In-store'], dtype=object)

**Handling Transaction Date column**

In [ ]:
df['Transaction Date'].unique()

array(['2023-09-08', '2023-05-16', '2023-07-19', '2023-04-27',
       '2023-06-11', '2023-10-06', '2023-10-28', '2023-11-07', 'ERROR',
       '2023-05-03', '2023-11-15', '2023-02-24', '2023-03-25',
       '2023-01-15', '2023-04-04', '2023-03-30', '2023-12-01',
       '2023-06-03', '2023-04-20', '2023-04-10', '2023-11-06',
       '2023-10-09', '2023-05-28', '2023-04-29', '2023-11-03',
       '2023-01-08', '2023-12-05', '2023-03-19', '2023-04-19',
       '2023-10-03', '2023-04-06', '2023-03-22', '2023-01-31',
       '2023-12-14', '2023-07-16', '2023-06-15', '2023-12-09',
       '2023-04-30', '2023-05-24', '2023-08-16', '2023-08-07',
       '2023-08-20', '2023-06-10', '2023-04-15', '2023-05-27',
       '2023-07-25', '2023-12-15', '2023-02-25', '2023-04-03',
       '2023-12-28', 'UNKNOWN', '2023-01-10', '2023-09-23', '2023-09-14',
       '2023-02-06', '2023-03-11', '2023-07-14', '2023-04-18',
       '2023-12-12', '2023-01-05', '2023-09-03', '2023-06-06',
       '2023-03-23', '2023-11-25', '2023-11-02', '2023-07-31',
       '2023-09-04', '2023-05-21', '2023-07-02', '2023-11-21',
       '2023-03-13', '2023-02-16', '2023-03-26', '2023-11-01',
       '2023-02-28', '2023-01-27', '2023-04-07', '2023-10-26',
       '2023-12-10', '2023-02-04', '2023-11-12', '2023-05-10',
       '2023-05-04', '2023-04-26', '2023-03-01', '2023-11-13',
       '2023-12-27', '2023-05-18', '2023-01-17', '2023-03-29',
       '2023-09-22', '2023-08-22', '2023-07-27', '2023-12-30',
       '2023-01-03', '2023-10-20', '2023-08-31', '2023-09-02',
       '2023-12-13', '2023-08-19', '2023-03-31', '2023-01-06',
       '2023-07-10', '2023-05-29', '2023-07-07', '2023-11-16',
       '2023-11-23', '2023-10-22', '2023-06-23', '2023-12-11',
       '2023-04-25', '2023-10-12', '2023-10-21', '2023-09-19',
       '2023-07-04', '2023-02-26', '2023-04-23', '2023-01-22',
       '2023-01-28', '2023-08-11', '2023-10-08', '2023-06-30',
       '2023-02-27', '2023-03-03', '2023-02-21', '2023-09-27',
       '2023-08-18', '2023-06-07', '2023-07-06', '2023-12-22',
       '2023-01-14', '2023-08-09', '2023-05-14', '2023-11-26',
       '2023-02-02', '2023-03-15', '2023-10-16', '2023-07-15',
       '2023-11-17', '2023-12-20', '2023-07-12', '2023-02-08',
       '2023-02-01', '2023-02-12', '2023-03-14', '2023-03-02',
       '2023-09-29', '2023-04-22', '2023-08-25', '2023-07-28',
       '2023-02-20', '2023-02-18', '2023-06-13', '2023-03-28',
       '2023-04-14', '2023-02-11', '2023-01-30', '2023-04-09',
       '2023-10-07', '2023-07-29', '2023-06-05', '2023-03-21',
       '2023-10-19', '2023-10-27', '2023-03-20', '2023-09-16',
       '2023-10-24', '2023-08-28', '2023-06-21', '2023-09-15',
       '2023-11-10', '2023-05-19', '2023-04-21', '2023-08-10',
       '2023-12-16', '2023-09-25', '2023-05-09', '2023-12-21',
       '2023-05-30', '2023-04-24', '2023-01-11', '2023-09-18',
       '2023-02-09', '2023-09-05', '2023-10-18', '2023-05-05',
       '2023-02-10', '2023-07-11', '2023-12-24', '2023-10-25',
       '2023-10-05', '2023-07-08', '2023-06-28', '2023-09-09',
       '2023-01-09', '2023-07-22', '2023-07-01', '2023-04-16',
       '2023-03-09', '2023-11-08', '2023-12-26', '2023-09-13',
       '2023-05-23', '2023-09-11', '2023-08-24', '2023-06-18',
       '2023-04-01', '2023-08-23', '2023-12-06', '2023-08-13',
       '2023-10-30', '2023-08-27', '2023-05-26', '2023-12-25',
       '2023-08-21', '2023-10-23', '2023-02-19', '2023-05-06',
       '2023-01-07', '2023-07-23', '2023-04-08', '2023-08-14',
       '2023-03-10', '2023-10-31', '2023-08-12', '2023-12-18',
       '2023-07-24', '2023-12-31', '2023-10-15', '2023-05-07',
       '2023-02-05', '2023-05-02', '2023-01-02', '2023-06-12',
       '2023-03-16', '2023-01-01', '2023-01-16', '2023-05-01',
       '2023-04-12', '2023-01-12', '2023-02-15', '2023-01-13',
       '2023-06-24', '2023-08-26', '2023-06-19', '2023-06-22',
       '2023-07-05', '2023-05-17', '2023-11-27', '2023-09-28',
       '2023-12-02', '2023-02-07', '2023-01-04', '2023-11-18',
       '2023-10-01', '2023-11-22', '2023-11-28', '2023-10-02',
       '2023-11-09', '2023-09-20', '2023-11-29', '2023-06-16',
       '2023-09-26', '2023-07-18', '2023-06-02', '2023-04-13',
       '2023-06-04', '2023-03-18', '2023-08-04', '2023-11-24',
       '2023-08-06', '2023-07-21', '2023-07-17', '2023-08-17',
       '2023-01-18', '2023-12-08', '2023-04-17', '2023-03-06',
       '2023-08-03', '2023-12-07', '2023-07-13', '2023-10-11',
       '2023-09-10', '2023-02-22', '2023-08-05', '2023-07-09',
       '2023-11-19', '2023-02-03', '2023-09-12', '2023-09-21',
       '2023-03-05', '2023-12-17', '2023-04-28', '2023-01-21',
       '2023-12-23', '2023-03-08', '2023-07-20', '2023-11-04',
       '2023-01-29', '2023-12-19', '2023-08-02', '2023-08-15',
       '2023-08-01', '2023-10-14', '2023-03-04', '2023-04-05',
       '2023-06-27', '2023-11-30', '2023-06-08', '2023-05-12',
       '2023-06-20', '2023-12-29', '2023-02-13', '2023-12-04',
       '2023-04-02', '2023-07-30', '2023-10-29', '2023-09-17',
       '2023-02-17', '2023-10-13', '2023-11-20', '2023-06-09',
       '2023-06-25', '2023-09-06', '2023-09-01', '2023-08-29',
       '2023-11-05', '2023-01-20', '2023-03-17', '2023-03-07',
       '2023-01-19', '2023-09-30', '2023-03-24', '2023-05-31',
       '2023-10-04', '2023-12-03', '2023-10-10', '2023-03-12',
       '2023-10-17', '2023-07-26', '2023-06-01', '2023-06-29',
       '2023-09-07', '2023-05-08', '2023-08-30', '2023-06-17',
       '2023-04-11', '2023-01-26', '2023-06-14', '2023-01-24',
       '2023-05-15', '2023-01-25', '2023-07-03', '2023-03-27',
       '2023-06-26', '2023-02-23', '2023-05-11', '2023-11-11',
       '2023-05-20', '2023-08-08', '2023-01-23', '2023-02-14',
       '2023-11-14', '2023-05-22', '2023-09-24', '2023-05-25',
       '2023-05-13'], dtype=object)

In [ ]:
df['Transaction Date'] = df['Transaction Date'].replace('UNKNOWN','2023-01-01')
df['Transaction Date'] = df['Transaction Date'].replace('ERROR','2023-01-01')

In [ ]:
df['Transaction Date'].unique()

array(['2023-09-08', '2023-05-16', '2023-07-19', '2023-04-27',
       '2023-06-11', '2023-10-06', '2023-10-28', '2023-11-07',
       '2023-01-01', '2023-05-03', '2023-11-15', '2023-02-24',
       '2023-03-25', '2023-01-15', '2023-04-04', '2023-03-30',
       '2023-12-01', '2023-06-03', '2023-04-20', '2023-04-10',
       '2023-11-06', '2023-10-09', '2023-05-28', '2023-04-29',
       '2023-11-03', '2023-01-08', '2023-12-05', '2023-03-19',
       '2023-04-19', '2023-10-03', '2023-04-06', '2023-03-22',
       '2023-01-31', '2023-12-14', '2023-07-16', '2023-06-15',
       '2023-12-09', '2023-04-30', '2023-05-24', '2023-08-16',
       '2023-08-07', '2023-08-20', '2023-06-10', '2023-04-15',
       '2023-05-27', '2023-07-25', '2023-12-15', '2023-02-25',
       '2023-04-03', '2023-12-28', '2023-01-10', '2023-09-23',
       '2023-09-14', '2023-02-06', '2023-03-11', '2023-07-14',
       '2023-04-18', '2023-12-12', '2023-01-05', '2023-09-03',
       '2023-06-06', '2023-03-23', '2023-11-25', '2023-11-02',
       '2023-07-31', '2023-09-04', '2023-05-21', '2023-07-02',
       '2023-11-21', '2023-03-13', '2023-02-16', '2023-03-26',
       '2023-11-01', '2023-02-28', '2023-01-27', '2023-04-07',
       '2023-10-26', '2023-12-10', '2023-02-04', '2023-11-12',
       '2023-05-10', '2023-05-04', '2023-04-26', '2023-03-01',
       '2023-11-13', '2023-12-27', '2023-05-18', '2023-01-17',
       '2023-03-29', '2023-09-22', '2023-08-22', '2023-07-27',
       '2023-12-30', '2023-01-03', '2023-10-20', '2023-08-31',
       '2023-09-02', '2023-12-13', '2023-08-19', '2023-03-31',
       '2023-01-06', '2023-07-10', '2023-05-29', '2023-07-07',
       '2023-11-16', '2023-11-23', '2023-10-22', '2023-06-23',
       '2023-12-11', '2023-04-25', '2023-10-12', '2023-10-21',
       '2023-09-19', '2023-07-04', '2023-02-26', '2023-04-23',
       '2023-01-22', '2023-01-28', '2023-08-11', '2023-10-08',
       '2023-06-30', '2023-02-27', '2023-03-03', '2023-02-21',
       '2023-09-27', '2023-08-18', '2023-06-07', '2023-07-06',
       '2023-12-22', '2023-01-14', '2023-08-09', '2023-05-14',
       '2023-11-26', '2023-02-02', '2023-03-15', '2023-10-16',
       '2023-07-15', '2023-11-17', '2023-12-20', '2023-07-12',
       '2023-02-08', '2023-02-01', '2023-02-12', '2023-03-14',
       '2023-03-02', '2023-09-29', '2023-04-22', '2023-08-25',
       '2023-07-28', '2023-02-20', '2023-02-18', '2023-06-13',
       '2023-03-28', '2023-04-14', '2023-02-11', '2023-01-30',
       '2023-04-09', '2023-10-07', '2023-07-29', '2023-06-05',
       '2023-03-21', '2023-10-19', '2023-10-27', '2023-03-20',
       '2023-09-16', '2023-10-24', '2023-08-28', '2023-06-21',
       '2023-09-15', '2023-11-10', '2023-05-19', '2023-04-21',
       '2023-08-10', '2023-12-16', '2023-09-25', '2023-05-09',
       '2023-12-21', '2023-05-30', '2023-04-24', '2023-01-11',
       '2023-09-18', '2023-02-09', '2023-09-05', '2023-10-18',
       '2023-05-05', '2023-02-10', '2023-07-11', '2023-12-24',
       '2023-10-25', '2023-10-05', '2023-07-08', '2023-06-28',
       '2023-09-09', '2023-01-09', '2023-07-22', '2023-07-01',
       '2023-04-16', '2023-03-09', '2023-11-08', '2023-12-26',
       '2023-09-13', '2023-05-23', '2023-09-11', '2023-08-24',
       '2023-06-18', '2023-04-01', '2023-08-23', '2023-12-06',
       '2023-08-13', '2023-10-30', '2023-08-27', '2023-05-26',
       '2023-12-25', '2023-08-21', '2023-10-23', '2023-02-19',
       '2023-05-06', '2023-01-07', '2023-07-23', '2023-04-08',
       '2023-08-14', '2023-03-10', '2023-10-31', '2023-08-12',
       '2023-12-18', '2023-07-24', '2023-12-31', '2023-10-15',
       '2023-05-07', '2023-02-05', '2023-05-02', '2023-01-02',
       '2023-06-12', '2023-03-16', '2023-01-16', '2023-05-01',
       '2023-04-12', '2023-01-12', '2023-02-15', '2023-01-13',
       '2023-06-24', '2023-08-26', '2023-06-19', '2023-06-22',
       '2023-07-05', '2023-05-17', '2023-11-27', '2023-09-28',
       '2023-12-02', '2023-02-07', '2023-01-04', '2023-11-18',
       '2023-10-01', '2023-11-22', '2023-11-28', '2023-10-02',
       '2023-11-09', '2023-09-20', '2023-11-29', '2023-06-16',
       '2023-09-26', '2023-07-18', '2023-06-02', '2023-04-13',
       '2023-06-04', '2023-03-18', '2023-08-04', '2023-11-24',
       '2023-08-06', '2023-07-21', '2023-07-17', '2023-08-17',
       '2023-01-18', '2023-12-08', '2023-04-17', '2023-03-06',
       '2023-08-03', '2023-12-07', '2023-07-13', '2023-10-11',
       '2023-09-10', '2023-02-22', '2023-08-05', '2023-07-09',
       '2023-11-19', '2023-02-03', '2023-09-12', '2023-09-21',
       '2023-03-05', '2023-12-17', '2023-04-28', '2023-01-21',
       '2023-12-23', '2023-03-08', '2023-07-20', '2023-11-04',
       '2023-01-29', '2023-12-19', '2023-08-02', '2023-08-15',
       '2023-08-01', '2023-10-14', '2023-03-04', '2023-04-05',
       '2023-06-27', '2023-11-30', '2023-06-08', '2023-05-12',
       '2023-06-20', '2023-12-29', '2023-02-13', '2023-12-04',
       '2023-04-02', '2023-07-30', '2023-10-29', '2023-09-17',
       '2023-02-17', '2023-10-13', '2023-11-20', '2023-06-09',
       '2023-06-25', '2023-09-06', '2023-09-01', '2023-08-29',
       '2023-11-05', '2023-01-20', '2023-03-17', '2023-03-07',
       '2023-01-19', '2023-09-30', '2023-03-24', '2023-05-31',
       '2023-10-04', '2023-12-03', '2023-10-10', '2023-03-12',
       '2023-10-17', '2023-07-26', '2023-06-01', '2023-06-29',
       '2023-09-07', '2023-05-08', '2023-08-30', '2023-06-17',
       '2023-04-11', '2023-01-26', '2023-06-14', '2023-01-24',
       '2023-05-15', '2023-01-25', '2023-07-03', '2023-03-27',
       '2023-06-26', '2023-02-23', '2023-05-11', '2023-11-11',
       '2023-05-20', '2023-08-08', '2023-01-23', '2023-02-14',
       '2023-11-14', '2023-05-22', '2023-09-24', '2023-05-25',
       '2023-05-13'], dtype=object)

In [ ]:
df.isnull().sum()

Transaction ID      0
Item                0
Quantity            0
Price Per Unit      0
Total Spent         0
Payment Method      0
Location            0
Transaction Date    0
dtype: int64